Repository WildCodeSchool/lyon-js-sept2020-p3-lafrica-front-office, pull requests merged in 2020-12, with the labels that each got.

#1 Header footer burger
  package-lock.json
  package.json
  public/LamLogo.PNG
  public/Logo_LAM_T2V.png
  src/components/App.css
  src/components/App.js
  src/components/footer/Footer.js
  src/components/footer/footer.css
  src/components/header/Header.js
  src/components/header/header.css
  src/images/BG-PRODUCT.png
  src/services/API.js
Labels: Ready for Prod

#4 Campaigns view
  src/components/App.js
  src/components/campaignsView/CampaignsView.css
  src/components/campaignsView/CampaignsView.js
  src/components/header/Header.js
  src/index.css
Labels: Ready for validation

#5 Login
  package-lock.json
  package.json
  public/index.html
  src/components/App.css
  src/components/App.js
  src/components/header/Header.js
  src/components/header/header.css
  src/components/home/Home.js
  src/components/home/home.css
  src/components/login/SignIn.js
  src/components/login/SignUp.js
  src/components/login/login.css
Labels: Ready for Prod

#2 Campaign detail
  package-lock.json
  package.json
  src/components/App.css
  src/components/App.js
  src/components/CampaignDetail/CampaignDetails.js
  src/components/CampaignDetail/CampaignDetails.scss
  src/components/footer/footer.css
  src/components/header/Header.js
  src/components/home/Home.js
  src/components/home/home.css
  src/components/login/SignUp.js
  src/components/login/login.css
Labels: Ready for Prod

#6 Create campaign page
  package-lock.json
  package.json
  src/components/create campaign/CreateCampaign.js
  src/components/create campaign/CreateCampaign.scss
  src/components/header/Header.js
Labels: Fixed - ready for prod

#7 Register
  package-lock.json
  package.json
  src/components/App.js
  src/components/header/Header.js
  src/components/header/header.css
  src/components/login/SignIn.js
  src/components/login/SignUp.js
  src/index.js
  src/services/API.js
Labels: Ready for Prod
