Repository WildCodeSchool/lyon-js-sept2020-p3-lafrica-front-office, pull requests merged in 2021-01, with the labels that each got.

#8 Register
  package-lock.json
  package.json
  src/components/App.js
  src/components/campaignsView/CampaignsView.js
  src/components/create campaign/CreateCampaign.js
  src/components/header/Header.js
  src/components/login/SignIn.js
  src/components/login/SignUp.js
Labels: Ready for Prod

#10 Text upload
  package-lock.json
  public/favicon.ico
  src/components/create campaign/CreateCampaign.js
  src/components/create campaign/CreateCampaign.scss
  src/components/create campaign/subcomponents/CustomizedSlider.js
  src/components/header/header.css
Labels: Ready for validation

#11 Dev
  package-lock.json
  package.json
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  src/components/create campaign/CreateCampaign.js
  src/components/create campaign/CreateCampaign.scss
  src/components/create campaign/subcomponents/CustomizedSlider.js
  src/components/header/Header.js
  src/components/header/header.css
  src/components/login/SignIn.js
  src/components/login/SignUp.js
Labels: Ready for Prod

#12 Protected routes
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/site.webmanifest
  src/components/App.js
  src/components/ProtectedRoutes/ProtectedRoutes.js
  src/components/campaignsView/CampaignsView.js
  src/components/create campaign/CreateCampaign.js
  src/components/create campaign/CreateCampaign.scss
  src/components/header/Header.js
  src/components/header/header.css
  src/components/login/SignIn.js
  src/context/UserContext.js
  src/hooks/useLocalStorage.js
Labels: Ready for validation

#13 Campagn creation
  src/components/App.js
  src/components/campaignsView/CampaignsView.js
  src/components/create campaign/CreateCampaign.js
  src/components/create campaign/CreateCampaign.scss
  src/components/create campaign/subcomponents/Contact.js
  src/components/create campaign/subcomponents/ContactsView.js
Labels: WIP
